
"""
recovery_engine.py
CARRERA-HUB v2
Enhanced Recovery Engine
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass
from enum import Enum, auto


class RecoveryStage(Enum):
    PREPARING=auto()
    FORCE_STOP=auto()
    WAITING=auto()
    RELAUNCH=auto()
    JOIN_PRIVATE_SERVER=auto()
    VERIFYING=auto()
    SUCCESS=auto()
    FAILED=auto()


@dataclass
class RecoveryResult:
    package:str
    success:bool
    stage:RecoveryStage
    message:str=""
    elapsed:float=0.0


class RecoveryEngine:
    """
    Executes recovery tasks generated by RecoveryScheduler.

    Pipeline:
    Force Stop -> Wait -> Relaunch -> Join PS -> Verify
    """

    def __init__(
        self,
        config_manager,
        state_manager,
        android_service,
        logger,
        launcher_engine,
        verification_engine,
        recovery_scheduler,
        private_server_manager=None,
    ):
        self.config=config_manager
        self.state=state_manager
        self.android=android_service
        self.logger=logger
        self.launcher=launcher_engine
        self.verifier=verification_engine
        self.scheduler=recovery_scheduler
        self.ps_manager=private_server_manager
        self._lock=threading.RLock()

    def recover(self,task):
        start=time.time()
        package=task.package

        with self._lock:
            try:
                self.state.mark_recovering(package)
            except Exception:
                pass

            try:
                self.logger.info(f"[RECOVERY] Starting {package}")
            except Exception:
                pass

            try:
                self.android.process.force_stop(package)
            except Exception as exc:
                self.scheduler.finish(package,False)
                return RecoveryResult(
                    package,False,
                    RecoveryStage.FAILED,
                    str(exc),
                    time.time()-start
                )

            delay=self.config.get("recovery","delay",default=10)
            time.sleep(delay)

            launch=self.launcher.launch_package(package)

            if not launch.success:
                self.scheduler.finish(package,False)
                return RecoveryResult(
                    package,False,
                    RecoveryStage.FAILED,
                    "Launch failed",
                    time.time()-start
                )

            if self.ps_manager:
                profile=self.ps_manager.profile
                if profile.valid and profile.deep_link:
                    try:
                        self.android.intent.open_uri(profile.deep_link)
                    except Exception:
                        pass

            verify=self.verifier.verify(package)

            if not verify.success:
                self.scheduler.finish(package,False)
                return RecoveryResult(
                    package,False,
                    RecoveryStage.FAILED,
                    "Verification failed",
                    time.time()-start
                )

            try:
                self.state.mark_online(package)
            except Exception:
                pass

            self.scheduler.finish(package,True)

            try:
                self.logger.info(f"[RECOVERY] Success {package}")
            except Exception:
                pass

            return RecoveryResult(
                package,
                True,
                RecoveryStage.SUCCESS,
                "Recovery completed",
                time.time()-start
            )

    def recover_pending(self):
        results=[]
        while True:
            task=self.scheduler.next_task()
            if task is None:
                break
            results.append(self.recover(task))
        return results
        
